### ISSUE TITLE
Change support for enums in form configuration

### ISSUE THREAD

**Issue by SBolsec** [croz-ltd/nrich#139]
## Basic information

* nrich version:
  v1.4.1
* Module:
  form-configuration

## Enhancement description

Change the `javascriptType` field from `object` to `string` for enum fields when fetching [`FormConfiguration`](https://github.com/croz-ltd/nrich/blob/master/nrich-form-configuration-api/src/main/java/net/croz/nrich/formconfiguration/api/model/FormConfiguration.java) instances for registered forms.

### Current behaviour

Currently the field `javascriptType` is set to `object` for enums.

### Wanted behaviour

Set the `javascriptType` to `string` for enums.

**Comment by agrancaric** [comment]
Resolved
