### ISSUE TITLE
Ommit message if not specified in notification response

### ISSUE THREAD

**Issue by nkescec** [croz-ltd/nrich#141]
## Basic information

* nrich version: 1.6.0
  
* Module: nrich-notification
  

## Additional information

Java version: 11.0.6

## Enhancement description

Messages that are missing for notification should not be substituted with default messages if some messages for that notification are already specified.

### Current behaviour

When message for a notification with action code `entity.create` is specified as so:

```properties
entity.create.title=This entity has been created!
```

default value for `content` is also included, even when not specified. In this case `content` part of notification is not needed so default message is also not needed.

### Wanted behaviour

Wanted behaviour is that if there are messages (_title_ or _content_) defined in the messages for that notification then only those specified messages are included into the notification. Otherwise default messages are used. This mode of work could be enabled with a new notification property.

### Possible workarounds

The workaround around this issue is to include this message into the file:

```properties
entity.create.content=
```

This clutters the `message.properties` file with needless additional properties that are empty.

**Comment by agrancaric** [comment]
I've opened a PR for removing default title, but for your case to work you will have to also disable registering of default notification messages with property nrich.notification.register-messages set to false, and define your own defaults (in this case blanks I think), you can try for content right away, title will need to wait for PR to be merged. For details see nrich-notification-messages file.

**Comment by agrancaric** [comment]
Closing this, if there are issues when we publish the version will reopen.
