### ISSUE TITLE
Sorting in SearchExecutor withouth Pageable

### ISSUE THREAD

**Issue by lkrapinec** [croz-ltd/nrich#143]
## Basic information

* nrich version:
  v1.6.0
* Module:
  net.croz.nrich.search.api.repository.SearchExecutor
* Link to the complete executable reproducer if available (e.g. GitHub Repo):

## Bug description
In method  <R, P> List<P> findAll(R request, SearchConfiguration<T, P, R> searchConfiguration) if request has sorting implemented it does not work. 
If we do that in method     <R, P> Page<P> findAll(R request, SearchConfiguration<T, P, R> searchConfiguration, Pageable pageable); everything work as intended (sort is applied).

### Steps to reproduce
...
  Request request1 = new Request();
    request1.setSortPropertyList(List.of(new SortProperty("dateOfCreation", SortDirection.DESC)));

    SearchConfiguration<Activity, Activity, Request> builder = SearchConfiguration.<Activity, Activity, Request>builder()
        .resolvePropertyMappingUsingPrefix(true)
        .build();

    List<Activity> a1 = activityRepository.findAll(request1, builder);

    request1.setPageSize(2);
    request1.setPageNumber(0);
    Page<Activity> a2 = activityRepository.findAll(request1, builder, PageableUtil.convertToPageable(request1));
### Expected behavior

 a1 = newerTask, olderTask
a2 = newerTask, olderTask

### Actual behavior

 a1 = olderTask , newerTask (no sort applied) 
a2 = newerTask, olderTask

**Comment by jzrilic** [comment]
Hello, I assume you want to execute the query with a defined sort without pagination. You can achieve that with `public <R, P> List<P> findAll(R request, SearchConfiguration<T, P, R> searchConfiguration, Sort sort)` method. Can you please confirm or elaborate in more detail if that's not the case?

**Comment by lkrapinec** [comment]
In this case everything works.
