### ISSUE TITLE
Custom validation ignored when using ValidationPriority groups

### ISSUE THREAD

**Issue by Waterhoax** [croz-ltd/nrich#155]
## Basic information

* nrich version: 1.7.1
* Module: registry

## Bug description

When using an `EntityCreateRequest` for registry entities, custom validation is ignored when using `ValidationPriority` groups, but works without them.

### Steps to reproduce

Works:
```
public class EntityCreateRequest {

    private Long id;

    @UniqueEntityName
    private String name;
    
    }
```

Doesn't work:
```
public class EntityCreateRequest {

    private Long id;

    @UniqueEntityName(groups = ValidationPriority.One.class)
    private String name;
    
    }
```

### Expected behavior

Validation triggers regardless of the presence of `ValidationPriority` groups,

### Actual behavior

Validation is ignored.

**Comment by agrancaric** [comment]
I think you're missing a `@GroupSequence` annotation, I've added a test case to verify see:

https://github.com/croz-ltd/nrich/pull/157

**Comment by Waterhoax** [comment]
I added the annotation and now it works :)

```
@GroupSequence({ EntityCreateRequest.class, ValidationPriority.One.class })
public class EntityCreateRequest {

    private Long id;

    @UniqueEntityName(groups = ValidationPriority.One.class)
    private String name;
    
    }
```
