### ISSUE TITLE
Additional code reformatting and cleanup

### ISSUE THREAD

**Issue by agrancaric** [croz-ltd/nrich#21]
## Basic information

* nrich version:
1.1.1
* Module:
Project
## Enhancement description
The continuation indent of 8 seems a bit too much, switch to using continuation indent to 4 and reformat code to match this change. There also seems to be some lines longer than 200 character, add line breaks where needed. Reformat AutoConfiguration tests to have asserts in a separate line. Remove extra empty lines where applicable. Order Lombok annotations and use minimal set. Introduce constants where missing.

**Comment by jsajlovic** [comment]
Fixed in #24
