### ISSUE TITLE
Add BOM/platform module

### ISSUE THREAD

**Issue by agrancaric** [croz-ltd/nrich#28]
## Basic information

* nrich version:
1.2.0
* Module:
Project

## Feature description

It would be good to have a bom/platform module that will provide all nrich dependencies as a bom and allow users to use that
for dependency version management./

### Current behavior

Users need to include versions for each dependency added.

### Wanted behavior

Users import bom/platform module and use the dependency versions defined there.

**Comment by jsajlovic** [comment]
Added in #29
